---
- name: configure base server
  hosts: webservers
  remote_user: centos
  become: yes


  tasks:

  - name: Install EPEL repo.
    yum:
      name: epel-release
      state: present


  - name: Install NTP
    yum: name=ntp state=installed
    tags: ntp


  - name: Copy over the NTP configuration
    get_url:
      url: https://raw.githubusercontent.com/shayharush/opsschol-ansible/master/session1/files/ntp.conf
      dest: /etc/ntp.conf
      mode: 0440
    notify:
      - restart ntpd

  - name: Make sure NTP is stopped
    service: name=ntpd state=stopped enabled=yes
    tags: ntp

  - name: Make sure NTP is started up
    service: name=ntpd state=started enabled=yes
    tags: ntp

  handlers:
  - name: restart ntpd
    service: name=ntpd state=restarted