---
- name: Install NTP
    yum: name=ntp state=installed
    tags: ntp


- name: Copy over the NTP configuration
  template:
    src: ntp.conf
    dest: /etc/ntp.conf
    mode: 0440
  notify:
    - restart ntpd

  - name: Make sure NTP is stopped
    service: name=ntpd state=stopped enabled=yes
    tags: ntp

  - name: Make sure NTP is started up
    service: name=ntpd state=started enabled=yes
    tags: ntp