---
- name: Add hostname to node1 in /etc/hosts
  lineinfile: dest=/etc/hosts line="10.0.0.253 node1.opsschool.com"

- name: create directory for index.html
  file:
    path: "{{apache_docroot}}"
    state: directory

- name: Add index.html to /var/www/html
  template:
    src: index.html
    dest: "{{apache_docroot}}/index.html"

- name: install apache
  yum:
    name: httpd
    state: latest

- name: start httpd
  service:
    name: httpd
    state: started
    enabled: yes

- name: Check that you can connect (GET) to a page and it returns a status 200
  uri:
    url: http://node1.opsschool.com
    return_content: yes
    register: result
    until: '"Ansible test page" in result.content'